### ISSUE TITLE
Spearmen have Red eyes while Grunts and Necrolytes have Blue

### ISSUE THREAD

**Issue by Zombie-Ryushu** [Wargus/war1gus#102]
Spearmen have Red eyes while Grunts and Necrolytes have Blue or whatever color swap has taken place during force re-color.

**Comment by timfel** [comment]
Yes, there are some other similar issues with for example spiders and scorpions or dragons and water elementals. I'm not going to fix those, the palette swap is a nasty hack as it is. Just redoing the swaps we have once we support the mac version will be annyoing enough. As long as the background color looks fine, I think it's good enough
