### ISSUE TITLE
Human Clerics cannot heal Orc Units in same force.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [Wargus/war1gus#103]
Human Clerics cannot heal Orc Units in the same force. In the original game, believe it or not, it was technically possible for a Human Cleric to heal an Orc Foe, and a Human peasant to repair an enemy town Hall. (Pointless but you could do it.) This would trigger the enemy unit to attack the healing Cleric.

In Stratagus, however, Human Clerics can only heal Human units, even in a setup with a dual race force.

**Comment by timfel** [comment]
Healing any unit should work now. Repairing enemy buildings doesn't, but do we really want that?
