### ISSUE TITLE
Attempt at making a port of Plains of Snow

### ISSUE THREAD

**Issue by Zombie-Ryushu** [Wargus/war1gus#105]
Attempt at making a port of Plains of Snow was kinda a catastrophe

**Comment by Zombie-Ryushu** [comment]
[plains.zip](https://github.com/Wargus/war1gus/files/130261/plains.zip)

**Comment by timfel** [comment]
What exactly where you trying to do? These kinds of bug reports aren't very helpful ;)

**Comment by Zombie-Ryushu** [comment]
I wanted a larger map to "stress" the AI of War1gus to look for faults in its behaviour without their being too many obstacles for it to get around. I wanted to port the Warcraft II Plains of snow map to Warcraft I to provide that. In my other custom map, Rescue Daemons, computer AI had been "surrendering" and reverting to mining village beaviour rather that escalating to Wolfrider and similar states of AI Scripting.

**Comment by timfel** [comment]
I don't understand the problem. Does using the editor not work for you? Just create a new map and go. You *cannot* derive your map from a shipped map, those use a different tile set. You *have* to create the map from scratch. Also, you cannot afterwards change the tileset - choose the tileset when creating the new map, then stick with it.

**Comment by Zombie-Ryushu** [comment]
The editor displays the map as a jumbled map. t crashed until I removed all the units, then it loaded, but the tiles are just bananas.

The point of this is, I want a large map that is larger than what War1 would provide with lots of mines and room to expand.

**Comment by timfel** [comment]
I understand what you want to do, but I don't understand what you think is the problem.

If you just go and click Editor->New map the new map will have correct tiles and you can just start to fill it with trees and such.

**Comment by Zombie-Ryushu** [comment]
I thought it was the optimal solution. Plains of snow exists in Warcraft and Starcraft

**Comment by timfel** [comment]
I still don't understand your problem. What do you mean by "it exists in Warcraft and Starcraft"? There is no way to import maps from any other Stratagus game into War1gus - any new map has to be recreated from scratch.

**Comment by Zombie-Ryushu** [comment]
I want to make "Plains of Snow WC 1 Edition with several forces at wrk.

**Comment by timfel** [comment]
Then you have to create a new map in war1gus and re-create Plains of Snow by hand.
