### ISSUE TITLE
Map Editor unuseable at low resolutions

### ISSUE THREAD

**Issue by Zombie-Ryushu** [Wargus/war1gus#106]
In the Map Editor, you cannot make trees. The forest.lua file won't let you make trees. forest_campaign will.

**Comment by timfel** [comment]
I cannot confirm this.

**Comment by Zombie-Ryushu** [comment]
Checking how update everything is.

**Comment by Zombie-Ryushu** [comment]
I re-extracted everything. It still won't let me make trees, The only paintable tiles are three types of grass, water, and vertical bridges only. If I switch the map type to  forest_campaign I can see everything, but, the map editor won't let me select that from the start, If I change the map type,  by editing the SMS File, It corrupts the map.

**Comment by timfel** [comment]
For me it looks like this, when I create a new map. How is it different for you?
![untitled](https://cloud.githubusercontent.com/assets/46235/13197909/b5445c26-d7fb-11e5-84f5-831a0c026ab4.gif)

**Comment by timfel** [comment]
And I'd be surprised if the forest_campaign tileset works at all.

**Comment by Zombie-Ryushu** [comment]
I only see one row of tiles, the tree and two bridge types are not present. You seem to be using a different screen resolution. Let me see if thats the problem

**Comment by Zombie-Ryushu** [comment]
Now I can see them, it was the screen resolution.

**Comment by Zombie-Ryushu** [comment]
So a better description of this bug is that the map editor icons are not visible at low resolutions.
