### ISSUE TITLE
Only a few questions

### ISSUE THREAD

**Issue by inukaze** [Wargus/war1gus#110]
Hi there. 

1 - The Format of all files must be ".gz" ?

2 - If i wanna translate Warcraft 1 , to 100% Spanish. the files must be "txt" inside of ".gz" or can be simple ".txt" ?

3 - If i wanna make new graphics data , i can ordered be name folder for example resolution ? or Texture Size ?
For Example inside "/usr/share/games/stratagus/war1gus/graphics/" foldes like

640x480 , 800x600 , 1024x768 (Resolution Names)
32 , 64 , 128, 256 , 512 , 1024 (Texture Size Names)

For make Better Graphics for Resolutions for High to Low.

Or for Example like the "Wyrmsun" (Steam) use Stratagus Too, make Folders inside for Backgrounds , tileset etc, and the game take it right ???

That's is all, thank you

**Comment by timfel** [comment]
Hi,

1. the format can be gz or uncompressed.

2. Just txt files are fine.

3. There is currently no way to have textures with different resolutions than the original. I was planning to add that at some point, but haven't gotten around to doing it. Right now all the pixel sizes in the lua files are hardcoded, unfortunately, they should instead be parameterized. If you are willing, you can try and take a look at the lua files and add a global preference to set the scale of the graphics

**Comment by inukaze** [comment]
Thanks for the quick answer.  

Ok i think i can make the text translations from English to Spanish
