### ISSUE TITLE
Feature Requests: Editable Campaign maps

### ISSUE THREAD

**Issue by Zombie-Ryushu** [Wargus/war1gus#111]
I'd like to be able to make multi-player cooperative campaign maps that are expansions of the default maps in the game.

**Comment by timfel** [comment]
It turns out to be fairly annoying to do this, unfortunately. It would require lots of experimenting, and it would then actually be faster to just redraw the maps. I will keep thinking about this, however.

**Comment by Zombie-Ryushu** [comment]
The issue is - or rather goal; is to expand the scope of the Campaign to permit a multi-player Co-Op experience in the vein of "For the Motherland". Additional Ally and Enemy forces present  on map.

**Comment by timfel** [comment]
The 3.0.0 release allows editing those maps
