### ISSUE TITLE
AI loop broken Orc 2 - 18

### ISSUE THREAD

**Issue by timfel** [Wargus/war1gus#112]

**Comment by Zombie-Ryushu** [comment]
Is this why enemy forces revert to "Area town behavior?"

**Comment by Zombie-Ryushu** [comment]
Attached Test map where AI just stops.
[Hamlet2.zip](https://github.com/Wargus/war1gus/files/1083435/Hamlet2.zip)

**Comment by Zombie-Ryushu** [comment]
Has anyone looked into this bug?

**Comment by timfel** [comment]
I haven't had time, no. The AI really isn't very good (although I played through the original game again recently and found the AI to be even worse in some maps and ways of playing - not an excuse for us, of course)

**Comment by Zombie-Ryushu** [comment]
Please try and work on this stuff, its been like two years. I don't understand the code well enough to work on it my self, and I'm finding more problems and not less.

**Comment by timfel** [comment]
Workaround in place, should be better a bit better now (but still a weak AI, but we have a separate issue for that)

**Comment by Zombie-Ryushu** [comment]
Wow I never expected these bugs addresssed.
