### ISSUE TITLE
A new Catapult Range Finding Glitch

### ISSUE THREAD

**Issue by Zombie-Ryushu** [Wargus/war1gus#113]
BUG: RangeTargetFinder.Compute out of range. size: 12, pos: -8, x: -1, xx: -1, y: 0, yy: -1BUG: RangeTargetFinder.Compute out of range. size: 12, pos: -2, x: -1, xx: -1, y: 0, yy: 0BUG: RangeTargetFinder.Compute out of range. size: 12, pos: -8, x: -1, xx: -1, y: 0, yy: -1BUG: RangeTargetFinder.Compute out of range. size: 12, pos: -2, x: -1, xx: -1, y: 0, yy: 0BUG: RangeTargetFinder.Compute out of range. size: 12, pos: -8, x: -1, xx: -1, y: 0, yy: -1BUG: RangeTargetFinder.Compute out of range. size: 12, pos: -2, x: -1, xx: -1, y: 0, yy: 0BUG: RangeTargetFinder.Compute out of range. size: 12, pos: -8, x: -1, xx: -1, y: 0, yy: -1BUG: RangeTargetFinder.Compute out of range. size: 12, pos: -2, x: -1, xx: -1, y: 0, yy: 0BUG: RangeTargetFinder.Compute out of range. size: 12, pos: -8, x: -1, xx: -1, y: 0, yy: -1BUG: RangeTargetFinder.Compute out of range. size: 12, pos: -2, x: -1, xx: -1, y: 0, yy: 0BUG: RangeTargetFinder.Compute out of range. size: 12, pos: -8, x: -1, xx: -1, y: 0, yy: -1BUG: RangeTargetFinder.Compute out of range. size: 12, pos: -2, x: -1, xx: -1, y: 0, yy: 0BUG: RangeTargetFinder.Compute out of range. size: 12, pos: -8, x: -1, xx: -1, y: 0, yy: -1BUG: RangeTargetFinder.Compute out of range. size: 12, pos: -2, x: -1, xx: -1, y: 0, yy: 0BUG: RangeTargetFinder.Compute out of range. size: 12, pos: -8, x: -1, xx: -1, y: 0, yy: -1BUG: RangeTargetFinder.Compute out of range. size: 12, pos: -2, x: -1, xx: -1, y: 0, yy: 0BUG: RangeTargetFinder.Compute out of range. size: 12, pos: -8, x: -1, xx: -1, y: 0, yy: -1BUG: RangeTargetFinder.Compute out of range. size: 12, pos: -2, x: -1, xx: -1, y: 0, yy: 0BUG: RangeTargetFinder.Compute out of range. size: 12, pos: -8, x: -1, xx: -1, y: 0, yy: -1BUG: RangeTargetFinder.Compute out of range. size: 12, pos: -2, x: -1, xx: -1, y: 0, yy: 0BUG: RangeTargetFinder.Compute out of range. size: 12, pos: -8, x: -1, xx: -1, y: 0, yy: -1BUG: RangeTargetFinder.Compute out of range. size: 12, pos: -2, x: -1, xx: -1, y: 0, yy: 0BUG: RangeTargetFinder.Compute out of range. size: 12, pos: -8, x: -1, xx: -1, y: 0, yy: -1BUG: RangeTargetFinder.Compute out of range. size: 12, pos: -2, x: -1, xx: -1, y: 0, yy: 0BUG: RangeTargetFinder.Compute out of range. size: 12, pos: -8, x: -1, xx: -1, y: 0, yy: -1BUG: RangeTargetFinder.Compute out of range. size: 12, pos: -2, x: -1, xx: -1, y: 0, yy: 0BUG: RangeTargetFinder.Compute out of range. size: 12, pos: -8, x: -1, xx: -1, y: 0, yy: -1BUG: RangeTargetFinder.Compute out of range. size: 12, pos: -2, x: -1, xx: -1, y: 0, yy: 0BUG: RangeTargetFinder.Compute out of range. size: 12, pos: -8, x: -1, xx: -1, y: 0, yy: -1BUG: RangeTargetFinder.Compute out of range. size: 12, pos: -2, x: -1, xx: -1, y: 0, yy: 0Thanks for playing Stratagus.

**Comment by timfel** [comment]
Fixed in stratagus master, the fix will be in the next release and already is in nightly builds

**Comment by timfel** [comment]
Fixed in stratagus master, the fix will be in the next release and already is in nightly builds
