### ISSUE TITLE
stretch window mode

### ISSUE THREAD

**Issue by legluondunet** [Wargus/war1gus#116]
Hello,
instead of choosing resolution, it will be better war1gus adapts the game screen to the window size, whatever the size. I think it's a stretch or scaled feature but keep aspect ratio?

Thank you for your help.

LGDN

**Comment by timfel** [comment]
What do you mean? The window should be reizeable?

**Comment by legluondunet** [comment]
"The window should be reizeable?"

Exactly! Like the window mode of ScummVM and other apps/games. 
It interesting to specify the resolution only for fullscreen mode.

**Comment by timfel** [comment]
Implemented in the latest master.
