### ISSUE TITLE
Setting up PATH ffmpeg theora timidity

### ISSUE THREAD

**Issue by jqubit999** [Wargus/war1gus#117]
I am new to ffmpeg, ffmpeg2theora and timidity.  Your readme tells me to set up those 3 thing but not how,  How do I install and setup the path to those three on windows?.  Also where do I download said items?

**Comment by timfel** [comment]
If you use the installer, they come with the bundle and you don't need to do anything.

**Comment by timfel** [comment]
I removed the confusing sentence
