### ISSUE TITLE
FLI_COPY, skipping chunk, input/output error

### ISSUE THREAD

**Issue by 2mg** [Wargus/war1gus#119]
Videos aren't properly converted, this happens a lot:

`Press [q] to stop, [?] for help
frame=   28 fps=0.0 q=-0.0 size=     558kB time=00:00:01.98 bitrate=2300.9kbits/
[flic @ 00000000003182a0] In chunk FLI_COPY : source data (63998 bytes) has inco
rrect size, skipping chunk
    Last message repeated 3 times
H:\DATA//hmap04.war: Input/output error
frame=   47 fps=0.0 q=-0.0 Lsize=    1329kB time=00:00:03.33 bitrate=3261.7kbits
/s
video:1319kB audio:0kB subtitle:0kB other streams:0kB global headers:3kB muxing
overhead: 0.707862%`

PS: Intro cinematic doesn't play the MIDI/SF2 music.

2.4.1 War1gus stable Win 7 x64. Tested the game in a VM, vids and intro music works fine.

**Comment by timfel** [comment]
I fixed this in master for linux. Unfortunately, the ffmpeg version we use for Windows doesn't support the same method, so on Windows, you'll still get these broken videos right now :/
