### ISSUE TITLE
Clarification - does Wargus apply official final patches to the game?

### ISSUE THREAD

**Issue by 2mg** [Wargus/war1gus#120]
WC2 can be patched to 1.4.
WC2 EXP can be patched to 1.5.

Do I need to install the game & exp first, patch it and then apply Wargus?

**Comment by timfel** [comment]
I'm not sure what those patches do, but I don't think they affect Wargus. Any unit stats are coded in Wargus itself, the only thing that is really extracted are maps, graphics, and texts. Unless the patches change those, there won't be any difference.

**Comment by 2mg** [comment]
Well those patches do this: 

http://wowwiki.wikia.com/wiki/Warcraft_II:_Tides_of_Darkness/Beyond_the_Dark_Portal_Patch_Information

So, is there any way to implement these patches? Like use WC2 + Exp + patch installation instead of pointing to WC2 ToD and BtDP when installing Wargus?

**Comment by 2mg** [comment]
Bump?

**Comment by timfel** [comment]
The patches are not applicable for us. Applying them won't change anything for us
