### ISSUE TITLE
My War1gus is Broken and Ruined (skipping chunk errors and other things)

### ISSUE THREAD

**Issue by feruenzerujkun** [Wargus/war1gus#121]
Hi, War1gus users, i'm new to War1gus and Wargus (Well, i do not have the original WC2 cd for Wargus).

When i first installed War1gus at July 4 of this year after installing Stratagus (Version 2.4.1 or 2.4.2 maybe), and it's having issues with the chunks, the cutscenes/movies/videos and gameplay (I can't press Escape key and other keys that will pause the game and save/load saved games).

I tried opening up the map editor part of the game, and it won't let me exit the game.
And i've tried checking out R.M. Strider's video on YT having a 100% working version of the game.

It's hard to find an issue with Stratagus' and War1gus' installs with the game CD (I do not want to do torrent versions of WC1 and WC2).

Here's my issues:
1: I'm using Stratagus 2.4.2 and War1gus 2.4.1 or 2.42.
2: I can't pause the game with F10 or Esc key.
3: The cutscenes/movies are buggy and glitchy due to chunk errors and file errors.
4: The music isn't playing after reinstalling 3-6 times.
5: I'm using an Windows 10 Alienware 17 R2 Laptop (That's the only computer i use for my important things like work and playing games).
6: I haven't checked my hardware and drivers.
7: I have a Hybrid Disc from the Warcraft 1&2 Battle Chest (I don't think my WC1 hybrid disc can work on War1gus. Tried installing it on my laptop, and it's giving me errors).

If you guys help me out with War1gus, comment/reply here so that i can read yours to see that's helpful.

One of my workmates on HIVE pyf told to use a program called Nero DiscSpeed to find out if my WC1 CD is defect free or not.
After i've tried it, the CD is 0.6 % damaged and 0.1 % bad on my ends because Track 01 has 0 MB and 0 quality on my ends. :(

I'd liked to send you guys screenshots and code examples about my problem with War1gus on github, and now i can't.
If so, i won't be able to install War1gus.
Please thank me for trying out War1gus, i mean it.

TIA! :)

**Comment by feruenzerujkun** [comment]
I guess nobody's helping me fix my War1gus. :\ 👎 

No more Stratagus, War1gus and Wargus for me. :(

**Comment by DinkyDyeAussie** [comment]
You need the DOS version of the Warcraft 1 and 2 cds. I am sure you can find them online in ISO format. I have never heard of the hybrid CD.

Is it extracting all the data?

Also War1gus is still really buggy. Wargus is the most stable. People are working on it, but it has waned alot over the last 2 years. Real life gets in the way.

In all honesty I really think the devs should have made it not to work with .lua files, and instead just done all the configuration in the source code. It would have made things easier, and alot more reliable.

**Comment by feruenzerujkun** [comment]
> You need the DOS version of the Warcraft 1 and 2 cds. I am sure you can find them online in ISO format.
Sorry, my family and i do not have old DOS versions of the WC1&2 CDs since WC1&2 (DOS and PC versions) came out 23-22 years ago (94-96). I don't think finding them online in ISO formats or on torrents could be a bad idea. I hope any online store like ebay or any old online store has DOS games have DOS CDs of WC1&2. :)

> I have never heard of the hybrid CD.
> Is it extracting all the data?
It is a 1996 WC1 Hybrid CD my family has years ago (Probably 96, 97 or 99 i think)
See image by clicking the link: https://www.hiveworkshop.com/media/for-pyf-to-see.121503/full?lightbox=1&last_edit_date=1530966352
I've tried using the Hybrid CD to extract the data for W1gus, and now i think i used a CD scanner thing i was trying to use to scan the CD, and it shows it says "bad/damaged".
I couldn't figure out a way to get War1gus working on my Alienware laptop.

> Also War1gus is still really buggy.  Wargus is the most stable. 
Yes, it is buggy to my opinions, R.M Strider from YT's War1gus is still working, the music, the cutscenes and the pause/esc/menu button works on his, but not mine at least.

I liked to play Warcraft2gus, but i do not have a WC2 original or expansion DOS or PC CD to install it.

> Real life gets in the way.
Yeah, most of the time.

> It would have made things easier, and alot more reliable.
Yeah, depends.

Anyway, thank you for your comment, DinkyDyeAussie.
I wish i have a version of War1gus that works perfectly like R.M Strider's W1gus. :-]

**Comment by timfel** [comment]
> 2: I can't pause the game with F10 or Esc key.

fixed

> 3: The cutscenes/movies are buggy and glitchy due to chunk errors and file errors.

this is only windows. I'm working on a fix.

> 4: The music isn't playing after reinstalling 3-6 times.

fixed on master with migration to sdl2

> 7: I have a Hybrid Disc from the Warcraft 1&2 Battle Chest (I don't think my WC1 hybrid disc can work on War1gus. Tried installing it on my laptop, and it's giving me errors).

Never seen that one, but if it extracts and starts it shouldn't be a problem
