### ISSUE TITLE
War1gus 2.4.2.1 keeps asking to extract data on every launch

### ISSUE THREAD

**Issue by gisveld** [Wargus/war1gus#131]
First of all: Nice work te bring this game back to life with so many improvements :)

I have an issue with the 2.4.2.1 installer. It does not ask for the original folder like the 2.4.1 intaller. 
First the 2.4.2.1 installer work's fine but then asks for the DATA.WAR file. After this the wartool is running and the game starts. But you have to do this everytime when you start the game.

How can i upgrade to the 2.4.2.1 version of the game without this repeating error??

**Comment by timfel** [comment]
The installer was changed between 2.4.1 and 2.4.2 to ask on first launch for the folder. If it's asking you multiple times, thats a bug.

**Comment by timfel** [comment]
I just tried again and it works as it should for me - the data is extracted on first launch and then it just starts. What OS are you on?

**Comment by gisveld** [comment]
I'm on Windows 10.

1. Starting game after installation gives this bug:
![image](https://user-images.githubusercontent.com/17231386/46700871-472cbe80-cc1e-11e8-926f-f6defd5c440a.png)
2. Then after selecting the DATA.WAR file wartools is running, en gives this bug:
![image](https://user-images.githubusercontent.com/17231386/46701020-ae4a7300-cc1e-11e8-8b77-796f95027873.png)
3. Click on 'OK' the game is launching, and play's ok.
By next startup: back to step 1...

**Comment by timfel** [comment]
The first window is not a bug that's expected. The second means there was an error during extraction, although I don't see anything wrong with the commandline.

**Comment by timfel** [comment]
I fixed a potential bug there, could you try with the latest build?

**Comment by gisveld** [comment]
I tried running the War1gus-2.4.2.1.exe again (clean install) , and at first it keeps putting the same bug. 

Then i tried this: running war1gus.exe on the commandpromt (cmd.exe), not with the link on my desktop. The same bug is showing, but the game starts without doing te extranction of war1tools. Thats was a huge improvement. 

Then i did a new start-up from windows (desktop-link), selected the DATA.WAR file (maybe 2 times) and now the game starts at once! From commandpromt and also from Windows.

So it's fixed for me now, but i think this little bug is still there. Maybe this information helps you with a permanend solution.

**Comment by timfel** [comment]
It would be expected that it still asks you the first time, just not multiple times. However, if we have some random bug during extraction, the game might start but the extraction didn't run to completion (so some data may be missing, possibly for later missions), and then it will keep trying again until it gets a full successful extraction

**Comment by gisveld** [comment]
It looks like if u completely remove this map C:\Users\XXX\AppData\Roaming\Stratagus **after** an uninstall (windows) of War1gus, and then do a clean install of the 2.4.2.1 version this bug does not appear!
