### ISSUE TITLE
Mac app does not contain war1gus executable

### ISSUE THREAD

**Issue by mikr123** [Wargus/war1gus#137]
The current downloadable app package for mac does only contain war1tool and stratagus.

Because of this OSX complains about corrupted app.

I managed to build the executable by myself and copyied it into the app.

I opened .travis.yml and took the following command from "before_script" secion which is only executed for "linux" .

```
curl -O -L https://github.com/Wargus/stratagus/archive/master.zip;
unzip master.zip;
cmake -DSTRATAGUS=stratagus -DSTRATAGUS_INCLUDE_DIR=$PWD/stratagus-master/gameheaders ..;
```
With this command stratagzs is build and war1gus is able to be build as well.

Imho  .travis.yml  should be modified to build stratagus for OSX as well, otherwise war1gus executable won't be build and is missing in the app file.

**Comment by mikr123** [comment]
Untested fix, attached.
[travis.txt](https://github.com/Wargus/war1gus/files/3060396/travis.txt)

**Comment by timfel** [comment]
Thanks, building now
