### ISSUE TITLE
War1gus cheat codes no longer work.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [Wargus/war1gus#142]
War1gus cheat codes no longer work.
I tried sally shears and pot of gold, nothing happened. I need the ability to see the map to supervise the computer behavior.

**Comment by gisveld** [comment]
Did u use 'corwin of amber' first to enable the cheat codes?

________________________________
Van: Zombie-Ryushu <notifications@github.com>
Verzonden: maandag 29 april 2019 13:44
Aan: Wargus/war1gus
CC: Subscribed
Onderwerp: [Wargus/war1gus] War1gus cheat codes no longer work. (#142)


War1gus cheat codes no longer work.
I tried sally shears and pot of gold, nothing happened. I need the ability to see the map to supervise the computer behavior.

**Comment by Zombie-Ryushu** [comment]
Yeah, it works now.
