### ISSUE TITLE
Wolf Raiders and Knights seem to run unnaturally fast

### ISSUE THREAD

**Issue by Zombie-Ryushu** [Wargus/war1gus#143]
Wolf Raiders and Knights seem to run unnaturally fast. They move much faster than in the DOS original.

**Comment by timfel** [comment]
Everything moves much faster than the DOS original by default. On my machine the slowest speed we allow is the same as the fastest that the original has in Dosbox on the same machine. Or do you mean they are faster in relation to the other units?

**Comment by Zombie-Ryushu** [comment]
They run their regular speed until the upgrades are applied. Then they bolt accross the screen at an absurd rate.

**Comment by timfel** [comment]
I made the upgrade less strong
