### ISSUE TITLE
Unkillable units/structures

### ISSUE THREAD

**Issue by John-Gee** [Wargus/war1gus#145]
Hello,

it's my first time using War1gus and Stratagus so I apologize if I'm missing something. I run it on Arch Linux using the aur package, and I use stratagus not from a release but from laster master.

At the end of chapter 3 for the Orcs I was not able to destroy any human building and had to cheat to pass the level.

Again in chapter 4 I'm unable to do anything to the slimes.

Since I've never used this before I do not know if it used to work or not so I have not tried bisecting it.

Thanks

**Comment by timfel** [comment]
I introduced a bug with the damage formula between releases, but since the Linux packages are updated between updates from master, it ended up in the package. It's fixed on master

**Comment by John-Gee** [comment]
Thank you!
