### ISSUE TITLE
War1gus uninstall

### ISSUE THREAD

**Issue by Sircrashalot** [Wargus/war1gus#147]
The uninstaller deleted my whole game folder...

**Comment by jerkstore369** [comment]
Honestly, this things is a piece of shit. Note to devs, if you're going to do something why don't you finish it instead of letting some half asses trash sit in the repository. This doesn't even work properly so it useless.

**Comment by timfel** [comment]
That is expected. Your savegames and the extracted data are in %APPDATA%/Roaming/Stratagus/data.War1gus and %APPDATA%/Roaming/Stratagus/wc1. Anything else you're missing?

**Comment by Sircrashalot** [comment]
Sorry i did not explain properly.
It deinstalled my whole game folder, with all included other games.
Not just war1gus.

**Comment by timfel** [comment]
Oh god, I'm so sorry. I don't know how this can happen, I've reviewed the code and tried this on a bunch of different systems... :-/

**Comment by timfel** [comment]
Closing since I haven't heard back and couldn't reproduce this even on three new machines and no one else reported this.
