### ISSUE TITLE
Compiled Issues for War1gus 2.4.1.

### ISSUE THREAD

**Issue by PizzaLawyer420** [Wargus/war1gus#150]
Wargus 2.4.1 Install process:
-Run the .exe
-choose files to create
-Choose Location of install
-Choose location of DATA.WAR
-Run war1tool.exe
-Copy/extract DATA.WAR
-Finish
-Run War1gus
-Play

Problems with 2.4.1:
-Max resolution is 1920x1080, **BUT** only windowed!
-Full Screen only allowed at 1024x765 at most.
-OpenGL/Open GL ES 1.1 doesn't require a restart despite saying it does.
-A complete un-install requires the removal of the Stratagos folder that can be found deeper within one's computer.
--Simply un-installing from the given menus, does NOT clear the system.
---_Even the option to un-install "Settings," does nothing._

-Map Editor is vague
--Placing a Start Location is weird.
--Numbering Players from 0, is also strange.
---This not to say its impossible to work, but does require some poking-around or fore-knowledge.
-Walls do not display the proper artwork when building nor do they display the proper tile when built.
--Sometimes its just a black square, sometimes its water, sometimes its just the pre-building tile.
-Knights and Wolves are fast. Even faster when upgraded.
-Only two maps for each tileset are available.
--But, for Dungeon, there's eight maps!
---At least **FOUR** of those maps are the same! **LITERALLY!!**
-Forest1 and Forest2 maps show more options for tiles, but these are not usable by the mapper on new maps.
--The tiles available on these four maps are NOT usable on others or on new maps!
--Slider for choosing the extra tiles gets stuck on the edge of the menu bar, cannot go across UI.
---It can, however, get around. But not through.
-No tiles showing bridges connected to land outside of Campaign.
-Swamp tileset and Dungeon tileset are also limited like the Forest tileset.
-Cannot place "wood," or anything that counts-as-wood on Dungeon maps.
-Tendency of crashing when making Dungeon maps.

-Units will sometimes freeze if several are selected and ordered to do something.
-Menu button in game UI does not work. 
--Okay, it _"works,"_ but the player has to click on an invisible button that is scaled to be much more smaller than the actual button.
-There is no hot-key for the in-game menu
-The player is not warned when an enemy unit is near their base.
--This is a unique feature to War1, and its exclusion is very noticeable.
--This warning was also accompanied by a string that displayed on the screen.
-'Cannot Build There,' sound is not used. (?)
-Enemy AI may or may not work at all in Non-Campaign.
--If it does work, it will not advance farther than a single Town Hall.
-AI only works 50% of the time.
--If it _does_ work, they will build and attack you.
--If it _doesn't_ work, they will remain at one worker.
--They seem to only work if the player is slow to build.
---An example would be if I spend my time building four more workers and putting roads down around me, the AI might actually build a base and attack me.
They typically rush out a Footman or Grunt then they follow that one up with a Foot or Grunt plus an Archer or Spearman. If the player, however, builds a barracks before the AI does, the AI will freeze. 
-Cannot ally with AI.
--If allied with an AI, they will not reciprocate. 
--If you do ally with an AI, they will still attack you and you cannot attack back.
---I know that's the point, but it seems pointless if they will not ally with you.
-Cannot choose player color. 
-If the player builds a road under a pre-exsisting Town Hall, the Town Hall will be unable to place any new roads.
-Catapult projectile spins in an arc then lands. Instead of moving directly towards the intended target.
--*I know you're trying to make it look better, but get it to work properly before getting fancy with it.*
-Repeated AI Error in Orc 3, number 18.
-Enemy units will not appear on the minimap until they attack.
-Ranged attacks do not reveal the attacking unit. No matter how close they are.
-No Score is calculated at the end of a game.
-Human Mission Briefing characters are not animated.
-Orc Mission Breifing characters are not animated.
-No 3D scene post-briefing is shown.
-Post mission 3D scene does not play.
-No cut-scenes at all.*
--Correction, Cut-scenes MIGHT play. But: they play twice and the are only black and white.
--So far, only Human Mission Cut-Scenes play.
-Wounded's "upgrade," can be canceled. Thus making them remain as they were.
--Even if damaged again, they do not try to upgrade again.
-Occasionally, there will be "invisible trees," that can be harvested. Typically, its just a single tile of trees that got turned into stumps too soon. 
-AI Lumber harvesting sometimes takes a random tree tile from a batch, rather than an adjacent tree tile. 
--Basically, instead of taking the closest trees when harvesting, they might take ones on the other side of the clump. 
-Allied AI will have their workers use allied structures for resource depositing. (Not a complaint)
-Projectiles should move in a straight line towards their target, there is no need for spinning projectile. This applies to Archers, Spearmen, Clerics, Magicians, Necrolytes, Warlocks AND Catapults!!
-No option to have allied(friendly) AI.
-If the option to build Town Halls is on, the AI will typically build one per Gold Mine on the map in Campaigns. 
--Its not 100% bad, but its not 100% good either. 
-Building Icons, except for the Gold Mine, seem to use the wrong pallete as they are mostly red.
--This is not about having the building icons reflect my team color. A Barracks is not a giant red blob.
-If playing as one Race during a campaign and then you choose to play a mission from the other Race, your unit icons will be colored the same as the first Race you played with. Ex; I played a Human mission, in which my side was Blue. If I finished/quit the mission and then played an Orc mission, my Orc Icons would be colored Blue rather than Red. 
--This only happens for the first mission you switch over to. If you play another mission immediately afterwards, then the icons are the appropriate colors. 
-Slimes are animated way too slow. 
-AI tends to break more often on Orc missions.
-Blue AI shows up as Black on minimap in Orc Campaign.
--Blue AI might have Red Icons. But Blue structures and units.
-Orc 6? Even if you kill everything on the map, it won't end.
--this is the map where the Tower HAS to survive! It cannot be destroyed or else you loose! 
--If the Tower is destroyed you DO lose. But you don't win if its the only thing left!
-Chopped trees on Swamp maps sometimes display as built roads.
-If two walkable tiles are very close to each other while still having water separate them, then it is possible for your units to move across the gap.
-Destroyed buildings artwork disappears randomly, tile by tile, rather than in sequence. 
^Some what rectified. But it still happens.
-If loading from a saved game, all pre-exsisting units and buildings have their colors replaced with Black.
-Occasionally, briefing text will be white instead of yellow.
-Swamp(1)? Orange Player cannot be reached unless they have chopped down all the near-by trees.
-Second to Last human Mission is supposed to be "Rockard and Stoneard," Mission title has been worded as; "Blackard and Stoneard." 
-The Menu option of allowing multiple Town Halls cannot be disabled once its been enabled.
--If you want it back, you have to re-start the game.

There, that's everything I've found so far that needs work or is bugged.

**Comment by timfel** [comment]
Slowly addressing these:

>  -Full Screen only allowed at 1024x765 at most.

Fixed on master with migration to SDL2 rendering

>  -Human Mission Briefing characters are not animated.
-Orc Mission Breifing characters are not animated.
-No 3D scene post-briefing is shown.
-Post mission 3D scene does not play.
-No cut-scenes at all.*
--Correction, Cut-scenes MIGHT play. But: they play twice and the are only black and white.
--So far, only Human Mission Cut-Scenes play.

The briefings and results screen are now animated, and Windows now uses the better cutscene conversion code that Linux already used, to fix issues with the videos

**Comment by timfel** [comment]
>  -Second to Last human Mission is supposed to be "Rockard and Stoneard," Mission title has been worded as; "Blackard and Stoneard."

Fixed

**Comment by timfel** [comment]
> -The Menu option of allowing multiple Town Halls cannot be disabled once its been enabled.
--If you want it back, you have to re-start the game.

Fixed

**Comment by timfel** [comment]
>  -Cannot ally with AI.
--If allied with an AI, they will not reciprocate.
--If you do ally with an AI, they will still attack you and you cannot attack back.
---I know that's the point, but it seems pointless if they will not ally with you.

Since this will require larger engine work, I've just disabled the options to ally with AI. You can now only ally with human players.

**Comment by timfel** [comment]
> -Units will sometimes freeze if several are selected and ordered to do something.

Do they freeze entirely? For me they only wait for a couple of seconds and then continue on their path. This is just like in the original, and at least in part desired.

**Comment by timfel** [comment]
>  -Repeated AI Error in Orc 3, number 18.

Fixed

**Comment by timfel** [comment]
>  -Catapult projectile spins in an arc then lands. Instead of moving directly towards the intended target.
--I know you're trying to make it look better, but get it to work properly before getting fancy with it.
>  -Projectiles should move in a straight line towards their target, there is no need for spinning projectile. This applies to Archers, Spearmen, Clerics, Magicians, Necrolytes, Warlocks AND Catapults!!

I've fixed the spinning issues. Catapult projectiles will still fly in an arc, but their animation is now correct. All other units projectiles fly straight and don't randomly spin anymore

**Comment by timfel** [comment]
>  -Menu button in game UI does not work.
--Okay, it "works," but the player has to click on an invisible button that is scaled to be much more smaller than the actual button.

Fixed. Click target is now as large as the menu button

> -There is no hot-key for the in-game menu

Hotkeys are now defined for this and other in-game menus

**Comment by timfel** [comment]
> -Orc 6? Even if you kill everything on the map, it won't end.
> --this is the map where the Tower HAS to survive! It cannot be destroyed or else you loose!
> --If the Tower is destroyed you DO lose. But you don't win if its the only thing left!

Fixed.

**Comment by timfel** [comment]
> -Chopped trees on Swamp maps sometimes display as built roads.

Should be fixed, there was an error with the tileset definitions for trees.

**Comment by timfel** [comment]
> -Cannot place "wood," or anything that counts-as-wood on Dungeon maps.
> -Tendency of crashing when making Dungeon maps.

Both these things should be better now. Warcraft 1 was not designed with a map editor in mind like Warcraft 2, and the tileset design shows that. There are simply not enough tiles in the original game to make a proper map editor that creates correctly looking terrain - many tiles only exist in very specific directions and so they have to be placed by hand (by which i mean - they need to be written textually into the map file). There is not much we can do about this, so the editor only gives you a subset of the tiles for which we can give a half-proper experience.

The dungeon tiles in particular really do not work for the editor. However, I made a new "building" that is only available on dungeon levels - a "dungeon entrance". It shows a forest outside the dungeon, and works like a gold mine but for trees. So the worker walks "out of the dungeon" to get wood, and brings it back inside.

**Comment by timfel** [comment]
Most of these issues are now fixed, work differently, or have explanations. Closing
