### ISSUE TITLE
2.4.3 issues

### ISSUE THREAD

**Issue by amigalover** [Wargus/war1gus#154]
With the new 2.4.3 version - on multiple Computers with Win10 and Win7 (new War1gus installs and upgraded ones) - there are these problems:

* structures can't be destroyed, the state keeps always the same 'green'
* with Level 2 upwards, the player has zero lumber and zero gold, but you can carry from mine or wood and when the values are rising
* in Level 3 there is a debug output:
  BUG: Please file a bug 'AI loop broken' with the Level and this number 18

So I hope there is an easy possibility to fix the problems, because the earlier version from War1gus is free from that.

With best regards :-)

**Comment by timfel** [comment]
Hi, thanks for the report:
* I introduced a bug with the damage formula, it's fixed on master and structures can once again be destroyed on master
* thanks for that report - I didn't notice it, fixed on master
* I'm looking into how to solve the root problem (the AI is bad), but a workaround is on master that at least restores the loop to functioning
