### ISSUE TITLE
Human 5: Immortal Enemy Buildings

### ISSUE THREAD

**Issue by daddychainmail** [Wargus/war1gus#157]
Similar like before. Lost 37 units against 1 Barracks. Had to cheat..

**Comment by daddychainmail** [comment]
Same problem on Human 6. Curious if this is a glitch caused by initial cheat. On Human 6, even my buildings were immortal (Yes, I removed cheats to test).

**Comment by amigalover** [comment]
hi, this seems to be the same as issue #154 
version 2.4.3 has a number of strange problems which weren't there in 2.4.1
Do you have the possibility to check all your issues with the previous war1gus 2.4.1 ?

**Comment by timfel** [comment]
Fixed on master. It was my mistake with the damage formula
