### ISSUE TITLE
Human 7: No peasant, no gold

### ISSUE THREAD

**Issue by daddychainmail** [Wargus/war1gus#159]
Same issue continues.

**Comment by daddychainmail** [comment]
Potentially solved. Must save peasants first?

**Comment by daddychainmail** [comment]
Although catapult issue from Human 6 persists.

**Comment by timfel** [comment]
I fixed the issue with 0 gold, but the starting amount for this level (confirmed also in my Dos version and on https://strategywiki.org/wiki/Warcraft:_Orcs_%26_Humans/Sunnyglade_(Human)) is 300 gold, so you *must* save the other peasants first.
