### ISSUE TITLE
Text Scroll often too fast

### ISSUE THREAD

**Issue by daddychainmail** [Wargus/war1gus#161]
This is especially noticeable at the epilogues and longer briefings.

Just finished playing. It made me smile, "but that is a story for another time..."

**Comment by timfel** [comment]
You're right, I slowed them down. It will be in the next release.

Glad you were able to finish the campaign despite the bugs, and thank you very much for reporting them! Playtesting is the most time-consuming part of game reimplementations, unfortunately...
