### ISSUE TITLE
AI loop Broken, Map Orc 3 Number 18.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [Wargus/war1gus#166]
AI loop Broken, Map Orc 3 Number 18.

**Comment by timfel** [comment]
It seems you are not running master, right? It's fixed there

**Comment by Zombie-Ryushu** [comment]
Can you produce a bump release to 2.4.4 that fixes these bugs?

**Comment by timfel** [comment]
we'll release 3.0.0 in August, it will have these fixes. it still a few hours of work to do a full release given all the different reps, and I don't have the time

**Comment by timfel** [comment]
master has a lot of core engine changes that aren't fully stabilized and back porting just some of the fixes to the 2.4.3 release is not trivial. since you seem to be compiling from source anyway, you could try the latest master? it would also help us to get more play testing for the new rendering, audio, and other engine changes :)

**Comment by Zombie-Ryushu** [comment]
I could, But that's not trivial. I also have a Windows using client to support as well who cannot compile things on his own.

**Comment by timfel** [comment]
For Windows we still build the installer on every commit: https://github.com/Wargus/war1gus/releases/tag/master-builds

**Comment by timfel** [comment]
For Linux making packages for unreleased versions is more difficult due to the different packaging strategies

**Comment by Zombie-Ryushu** [comment]
I can provide RPM Spec Files.

**Comment by timfel** [comment]
We'd also need servers to build them and places to host them. We currently build on Travis (which means Ubuntu) and host the packages on Launchpad (thus Ubuntu). I think in the medium term our best bet is actually building Flatpaks or Snaps.

**Comment by timfel** [comment]
But if you can create CI config files to build the rpm packages e.g. on some other CI service that has Fedora or RedHat or whatever RPM using distribution people use these days, we can include them

**Comment by Zombie-Ryushu** [comment]
It appears that Stratagus now requires openmpi.
