### ISSUE TITLE
Buildings seem invincible in War1gus.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [Wargus/war1gus#167]
Buildings seem invincible in War1gus. I was playing Map3 of the Orc Campaign, I seemed unable to damage any buildings, even with corwin of Amber turned on.

**Comment by Zombie-Ryushu** [comment]
They are not fully invincible. Catapults and the Code that amplifies your damage does destroy buildings. But that's all.

**Comment by ipochto** [comment]
There was a bug with damage formula. Fixed in master.

**Comment by Pulfer** [comment]
Fixed by this commit? https://github.com/Wargus/war1gus/commit/f425b7301732f5a0841807e260ea183a3856d0c9

**Comment by timfel** [comment]
It was fixed here 033d400aaceb055316ca1dda374bae6a967e2654, but the damage formula from the official Warcraft documentation does things to the balancing that I don't like, so I disabled it in the commit you linked

**Comment by Zombie-Ryushu** [comment]
What commit fixes the AI just giving up? That's a problem too.

**Comment by timfel** [comment]
> What commit fixes the AI just giving up? That's a problem too.

none. the issue you opened is still open: https://github.com/Wargus/war1gus/issues/107
