### ISSUE TITLE
Installer generates Corrupt results on War1gus Stable

### ISSUE THREAD

**Issue by Zombie-Ryushu** [Wargus/war1gus#168]
War1gus (war1tool) 2.4.3 generates corrupt installs by failing to copy over some files from the contrib/ and scripts/ folders. during installation. This can be worked around by simply copying missing folders. 

This may be unrelated, but it's also the case on the Windows version, that war1tool cannot find ffmpeg or avconf, and will fail to extract the movies and music. This appears to be a $Path issue.

**Comment by timfel** [comment]
afaict this doesn't affect master
