### ISSUE TITLE
Request : Disable the Pixel-art scaling algorithm

### ISSUE THREAD

**Issue by 77Mynameislol77** [Wargus/war1gus#171]
It doesn't look great used on the warcraft 1 sprites

**Comment by 77Mynameislol77** [comment]
Tried just scaling down the sprites, that make the sprites themselves look better but the game crashes probably due to inconsistencies in the sprite sizes.

**Comment by timfel** [comment]
Can you tell me which version you are using? There are two independent scalers in use, the OpenGL shader based scaler that is done at runtime, and the scaling done during extraction. Which one do you mean?

**Comment by 77Mynameislol77** [comment]
The one during extraction

**Comment by timfel** [comment]
Hm, this is a bit annoying to do, it will need some work. With out the advmame2x scaling during extraction, the xBRZ scaler at runtime doesn't look good.

**Comment by timfel** [comment]
There's only another scaler if you activate it explicitly in the lua scripts. So by default there's one scaler. Your Wargus looks squished, it should be 640x480 as the default resolution

**Comment by timfel** [comment]
I think the squishing is one of the problems in your screenshot. afaict the engine assumes 640x480 and scales the graphics when you use 640x400, which adds to the bad aliasing effects. Another issue is of course the font. We don't extract the original font and instead use a contributed one that needs to be replaced (there's issue #126 for that)

**Comment by 77Mynameislol77** [comment]
The original game's native resolution is 320x200, scaling that up to 640x480 might explain the issues. It should scale to 640x400, not 640x480

**Comment by timfel** [comment]
but original game has non-square pixels, it's aspect ratio should be what 640x480 gives you.  the problem is that there's nyto easy way have both, I believe. the best option may be to pre-sale the graphics to 4 by 5, so the minimum resolution would be 1280x1000

**Comment by timfel** [comment]
Interestingly, I don't how you're running the original, but Dosbox seems to support the non-square pixels correctly, and the image looks much more stretched vertically:
![image](https://user-images.githubusercontent.com/46235/94902115-f9a75d00-0497-11eb-9f9f-d8403a5b0ce3.png)

**Comment by timfel** [comment]
What we should probably do is not to scale anything at all, set the default resolution to 320x200, and then use the SDL features to scale the output window in the end (and then pixel art scalers can be applied at this stage)

The annoying part is just going to be to go through all the lua files here an change all the pixel numbers for the new resolution

**Comment by 77Mynameislol77** [comment]
Here's an old screenshot of my CRT playing warcraft 1, it doesn't look stretched here, I hope it helps. 
![20181112_181830](https://user-images.githubusercontent.com/35608876/94904078-0aa59d80-049b-11eb-8066-f375b1621bbc.jpg)

**Comment by 77Mynameislol77** [comment]
I have an idea, maybe scale it like the old CRTS do? Instead of stretching the pixels, it should automatically add space between them, sort of emulating scanlines, that way the game will look faithful to the original. But maybe keep that only as a ingame shader option?

**Comment by 77Mynameislol77** [comment]
But yeah, setting the resolution internally to 320x200 seems like the way to go

**Comment by timfel** [comment]
Sorry, I have very little time right now. Adding the CRT shader is very simple, we already support just taking shaders from e.g. libretro and just dropping them into the installation folder.

This change isn't hard, it just takes a while since we have to manually go through all the Lua files in the repo and adjust all places where we use pixel sizes for loading graphics or pixel-exact positions. Most of them should just be divided by 2, I guess.

The other thing is the stretching, but it really also isn't very hard. Right now we enforces aspect-correct scaling in SDL, but we just need to tell it that it has to allow scaling up to 1:1.2 also, and then it'll be stretched just right.

**Comment by timfel** [comment]
N.b.: I've started working on this, but it means I need to review almost every single lua file in this repository, so it is slow going

**Comment by timfel** [comment]
Ok, it's done, I think. Here it is with CRT shader
![image](https://user-images.githubusercontent.com/46235/101727576-060dee80-3ab5-11eb-9952-85d424f680b0.png)

Here without the CRT shader:
![image](https://user-images.githubusercontent.com/46235/101727636-25a51700-3ab5-11eb-940e-fb118984202a.png)

And here with xBRZ:
![image](https://user-images.githubusercontent.com/46235/101727651-305fac00-3ab5-11eb-8751-d26283b6a71e.png)

**Comment by timfel** [comment]
Compare for reference this map in dosbox for the original:
![image](https://user-images.githubusercontent.com/46235/101727785-7583de00-3ab5-11eb-95ce-981803a9b214.png)

**Comment by timfel** [comment]
And of course you can just drop in shaders from libretro, for example, here's another CRT shader from there:
![image](https://user-images.githubusercontent.com/46235/101891118-e86a8300-3ba1-11eb-8444-9efa32901fd0.png)

**Comment by 77Mynameislol77** [comment]
Sorry for not responding earlier but I forgot my password and was locked out from logging in.

Absolutely fenomenal work you've done, I love it!

I really appreciate the time and efforts you put into this, on the behalf of the warcraft community, I thank you. 

I have but one question, since you mentioned libretro, does it work with CRT Royale? It's probably the best crt shader ever made

**Comment by timfel** [comment]
I doesn't work with CRT Royale unfortunately, that shader needs a lot of extra features that aren't supported in Stratagus. Stratagus only supports single pass shaders, e.g., most anything that is a single `.glsl` file in this repo: https://github.com/libretro/glsl-shaders

But in that repo you can see that crt-royale is really multiple filter passes (https://github.com/libretro/glsl-shaders/tree/master/crt/shaders/crt-royale/src)
