### ISSUE TITLE
macOS version doesn't work

### ISSUE THREAD

**Issue by pleasejustgo** [Wargus/war1gus#172]
Latest version doesn't work on macOS Mojave. Double click War1gus, some b.s. message comes up then it wants me to pick data.war. So I choose it from the DATA folder from a legit copy of warcraft 1 from gog. I get the message "There was an error copying the data, could not discover contributed directory path."

**Comment by timfel** [comment]
I've dropped support for macOS, because Apple seems to be actively making it harder and harder for cross-platform software to build, test, and ship without buying any Apple dev tools or licenses :(
