### ISSUE TITLE
War1gus-3.0.0 Midi volume loud

### ISSUE THREAD

**Issue by G2Gen** [Wargus/war1gus#173]
Hi,

I recently downloaded War1gus-2.4.3. The volume control (Midi vs sound effects) was great.  Unfortunately though in this version you cannot destroy buildings.
- I tried to fix the building error (on my machine for War1gus-2.4.3), but could not find the relevant file is *.lua. Where could I 
 correct this? Which software language is the mod in?. Obviously this ticket has already been closed, and thus V3.0.0 created).

In War1gus-3.0.0, the midi music is too loud! When you turn down the music, you also turn down the sound effects which is detrimental to overall enjoyment! What I want is to have loud SX and soft music.

- Again I tried to reduce the midi volume (on my machine for War1gus-3.0.0 with lua files), but was unsuccessful. 

If you make the requested mod (or inform me how to mod it on my machine), I would be happy to play through the game and give you my testing feedback (The hardest part of any testing program).

I don't see any point in playing an older version of the game as you have incorporated a number of commits in the last few months.

Many thanks, 
G2Gen.
(P.s. this is a Windows 10 install)

**Comment by G2Gen** [comment]
P.s. This is a Windows 10 install.

**Comment by timfel** [comment]
Thank you for the report!

I noticed the issue with volume on the 3.0.0 branch. I will fix this hopefully soon. 3.0.0 should still be released this year, since there is lots of changes we still need to review and playtest a lot of parts on different platforms

**Comment by timfel** [comment]
Sound volume should be fixed on master, but it will need a rebuild of the executable.
