### ISSUE TITLE
[3.0.0] Black screen with music playing

### ISSUE THREAD

**Issue by mgtroyas** [Wargus/war1gus#177]
I just fresh installed War1gus 3.0.0, on Windows 10, i5-7600k, Radeon RX580. Data was extracted from WC1 CD image. Opening cinematics were played. Then when I presume the main menu should be shown, the screen gets black, but music starts to play.

[stdout.txt](https://github.com/Wargus/war1gus/files/5723475/stdout.txt)
[stderr.txt](https://github.com/Wargus/war1gus/files/5723476/stderr.txt)

**Comment by timfel** [comment]
Could you open the file preferences.lua in your "My Documents/Stratagus/wc1" directory and make sure the setting ShaderName is set to "none"?

**Comment by mgtroyas** [comment]
That file doesn't exist on that path. The directory is empty.

**Comment by timfel** [comment]
Please try putting the preferences.lua attached file into the `wc1` folder:

[preferences.zip](https://github.com/Wargus/war1gus/files/5724389/preferences.zip)

**Comment by mgtroyas** [comment]
Yes, now it starts correctly.

**Comment by timfel** [comment]
Ok, thank you for the report. I had it set to "CRT" shader by default when no preferences are found, but apparently that shader has problems on your hardware or drivers. I have access to an RX590 that I can try on in a couple of weeks, so far I've only been testing this on Nvidia and Intel 3d accelerators and assumed it works fine everywhere. I was clearly mistaken.

**Comment by timfel** [comment]
Out of interest, can you let me know if the other built-in shaders work when you select them in the options->preferences menu?

**Comment by mgtroyas** [comment]
The first three (xBRZ, CRT and VHS) generate a black screen. All others work fine on my system.

**Comment by timfel** [comment]
All others? Did you add more shaders from the retroarch project?

**Comment by timfel** [comment]
ah, forget my comment, I forgot we ship other shaders with war1gus

**Comment by timfel** [comment]
Thanks!

**Comment by timfel** [comment]
Fixed in master, will be in next release.

**Comment by mgtroyas** [comment]
Great!
