### ISSUE TITLE
fullscreen option bug

### ISSUE THREAD

**Issue by legluondunet** [Wargus/war1gus#178]
sometimes when fullscreen option is checked, game show in a window et vice et versa.

On this capture, the game is in fullscreen, but the option is not checked:

![Capture d’écran de 2020-12-31 09-37-10](https://user-images.githubusercontent.com/325405/103431906-10189e00-4bd8-11eb-8eeb-b1fc6461c7f0.png)

**Comment by timfel** [comment]
Fixed
