### ISSUE TITLE
menu resolution outside screen

### ISSUE THREAD

**Issue by legluondunet** [Wargus/war1gus#179]
Hello,

on these capture you can see the resolution menu is badly located and menu shows outside screen, you can not choose a resolution. 

![Capture d’écran de 2020-12-31 09-30-33](https://user-images.githubusercontent.com/325405/103431931-67b70980-4bd8-11eb-8940-9ea7897ae77a.png)

**Comment by timfel** [comment]
Fixed in master. Will be in the next release
