### ISSUE TITLE
Bitdefender not accepting War1gus/Wargus/War2gus (Treated as Malware by the AV software) - Report/Log/List Only, no anything really, sorry : (

### ISSUE THREAD

**Issue by feruenzerujkun** [Wargus/war1gus#180]
AntiVirus Software:
Bitdefender

Reported/Remembered Date:
Tuesday, July 14th, 2020 (7/14/2020)

Threat Name:
Atc4.Detection (on All War1gus, Wargus, & War2gus data)

Disc:
1996 Warcraft: Orcs and Humans DOS and Macintosh (Hybrid Disc contain DATA.WAR, the file required for installing War1gus)

Version of War1gus Installed:
Possibly 2.4.3, 2.4 or 3.0.0

Affected Files (Treated as Malware by Bitdefender):
War1gus-2.4.3.exe
War1gus-2.4.exe
War1gus-3.0.0.exe
War1gus-3.0.1.exe

Installed/Tested on:
Windows 10 (not 7, 8, etc),
on an Alienware 17R2 (AW17R2) laptop

Cause of Atc4.Detection happening:
Possibly opening up the Map Editor or anything else valuable,
or trying to make a custom map on War1gus probably

Allow to keep as added to exceptions on AV software:
Yes or no depending on comments, replies or anything

Status:
Quarantined on Tuesday, July 14th, 2020 (7/14/2020)

Note to @timfel 
Just giving this log to you,
i would like install War1gus unless
I am comfortable enough to add it
exceptions on any AV program i am using
making the game unrunnable to unusable to be
treated as malware (e.g Atc4.Detection, etc)
by my used AV software Bitdefender for somehow.
Anything wrong going on, since i'm not
probably good with keyboard messaging and commenting
or anything months ago, let me know.
Thanks,
~Report given to @timfel, creator of War1gus and Wargus/War2gus for given details by @feruenzerujkun

**Comment by timfel** [comment]
Hi. I'm not familiar with your AV software, but most software flags our binaries because they are not signed. However, this is an open source project and I don't plan on buying a signing certificate just because of this. So I'm sorry, unless someone can donate a certificate, I don't think we can fix this.
