### ISSUE TITLE
Can't spawn peasants after trying to build road inside Town Hall

### ISSUE THREAD

**Issue by asbernardi** [Wargus/war1gus#182]
Hi!

Steps to reproduce:

1. Start solo game (Race Human, ForestMap1).
2. Build Town Hall.
3. Build road bordering upper part of Town Hall.
4. Build road inside Town Hall, near road built on step 3.
5. Try and fail to create peasants (gold is discounted).

Video showing issue: https://discord.com/channels/780082494447288340/780082494447288344/825700479379963914

Thanks!

**Comment by timfel** [comment]
Found the issue, it happens specifically when building at the top left of the townhall. The code then wants the townhall to "walk" there, and the entire building just breaks

**Comment by timfel** [comment]
Fixed on master

**Comment by asbernardi** [comment]
Thank you @timfel !
