### ISSUE TITLE
unable to change key bindings (intentional?)

### ISSUE THREAD

**Issue by timfel** [Wargus/war1gus#204]

**Comment by amigalover** [comment]
thank you for your effort
seems to work like it should (till level 3 no problems found)

**Comment by timfel** [comment]
@amigalover not sure why the comment is on this issue, but thanks ;)

Also, from your name I take it that you might be interested that I'm working on a new engine to play Warcraft 1 on Amiga OCS machines :)

**Comment by amigalover** [comment]
@timfel I wanted to left a simple comment for your development, but not open a new issue :)

Yes I'm a fan of the good old times and glad to hear that you try to port it to Amiga systems - but the reqs are a bit higher than a normal (A500) OCS system can handle. Don't cut it down too much, keep in mind most Amiga systems are pretty upgraded to min 1MB Chip + 2MB fast RAM, maybe it's easier for you to take an 68020/8MB system (f.e. A1200) as standard.
May I contribute sth to that project as a non-coder?
