### ISSUE TITLE
summoning water element, CTD when you try cancel wizard focus

### ISSUE THREAD

**Issue by Lagi7** [Wargus/war1gus#213]
sometimes when my water elements die in combat, the Conjurer /warlock  keep staying after in meditation phase. when i click myself to cancel summoning the game CTD.

because there is no more water elemental / Demon to remove

DefineButton({ Pos = 5, Level = 0, Icon = "icon-cancel",
  AlwaysShow = true,
  Key = "esc", Hint = "~<ESC~> BREAK SUMMONING",
  ForUnit = {"unit-warlock-during-summoning"},
  Action = "callback",
  Value = function(caster)
     local daemon = CasterToDaemonMap[caster]
     if daemon then
        table.remove(CasterToDaemonMap, caster)
        table.remove(DaemonToCasterMap, daemon)
        **RemoveUnit(daemon)**
        TransformUnit(caster, "unit-warlock")
        SetUnitVariable(caster, "Mana", 1)
     end
end})

**Comment by timfel** [comment]
Fixed with Wargus/stratagus commit b3b19b6aa
