### ISSUE TITLE
key shortcut hint is not coresponding with actual key

### ISSUE THREAD

**Issue by Lagi7** [Wargus/war1gus#215]
many instances in buttons:

line 294:
Key = "b", Hint = "BUILD ~!CATAPULT",
should be f.ex  
Key = "c", Hint = "BUILD ~!CATAPULT",

316:
Key = "t", Hint = "TRAIN ~!CONJURER",
should be
Key = "c", Hint = "TRAIN ~!CONJURER",

148
Key = "s", Hint = "FAR ~!SEEING",
should be (as spell research)
Key = "f", Hint = "~!FAR SEEING",

254
should be (more handy)
Key = "c", Hint = "BUILD ~!CHURCH",

orcs upgrade keys are very good. A like attack, and S shield, keyposition on keyboard is great, and shield is used as stop button, I suggest mirroring that setup
326
Key = "w", Hint = "UPGRADE S~!WORD STRENGTH",
Key = "h", Hint = "UPGRADE S~!HIELD STRENGTH",
should be (as per orcs)
Key = "a", Hint = "UPGR~!ADE SWORD STRENGTH",
Key = "s", Hint = "UPGRADE ~!SHIELD STRENGTH",

353 , 359 - this one is just very annoying
  Key = "u", Hint = "~!UPGRADE ARROW STRENGTH",
should be
  Key = "a", Hint = "UPGRADE ~!ARROW STRENGTH",

-------------orcs-----------
284
Key = "f", Hint = "TRAIN ~!GRUNT",
Key = "g", Hint = "TRAIN ~!GRUNT",

289
Key = "s", Hint = "TRAIN ~!SPEARMAN",

294
Key = "c", Hint = "BUILD ~!CATAPULT",

299 304 310
Key = "r", Hint = "TRAIN ~!RAIDER",

316
Key = "w", Hint = "TRAIN ~!WARLOCK",

321
Key = "c", Hint = "TRAIN ~!NECROLYTE",
should be (this is good because it mirror cleric, better key position)
Key = "c", Hint = "TRAIN NE~!CROLYTE",

353
Key = "u", Hint = "~!UPGRADE SPEAR STRENGTH",
should be 
Key = "a", Hint = "UPGRADE SPE~!AR STRENGTH",

379
Key = "d", Hint = "RESEARCH RAISE ~!DEAD",
should be (so its the same as casting spell key)
Key = "r", Hint = "RESEARCH  ~!RAISE DEAD",
--------------
most important change, pressing P is too far away
277
Key = "e", Hint = "TRAIN P~!EASANT",
Key = "e", Hint = "TRAIN P~!EON",

**Comment by timfel** [comment]
Hi, thank you for these really good and detailed issues. I don't know if I'll have time to fix these before December. If you would like to contribute the fixes, it's pretty easy these days by going to `github.dev/Wargus/war1gus` and then editing the files and committing. You can then send a pull request and I will merge them :)

**Comment by Lagi7** [comment]
thanks, 
I will learn how to do the pulls
