### ISSUE TITLE
restarting solo scenario always end with CTD

### ISSUE THREAD

**Issue by Lagi7** [Wargus/war1gus#219]
also some maps are CTD during start, not sure yet about the rule.

campaign maps restart fine.

**Comment by timfel** [comment]
I just tried and it works fine on my machine. IS there any output in stderr.txt or stdout.txt (if on Windows) or in the terminal (if on Linux)

**Comment by Lagi7** [comment]
stderr ":

Can't find icon 
Can't find icon 
Can't find icon 
Can't find icon 
Can't find icon 
Can't find icon

**Comment by timfel** [comment]
hm, that's completely normal. weird

**Comment by Lagi7** [comment]
it works now! i can restart without CTD
