### ISSUE TITLE
mana regenerate too fast

### ISSUE THREAD

**Issue by Lagi7** [Wargus/war1gus#232]
i just check vanilla warcraft1
mana reg is super slow

in war1gus it take seconds to have 100.

in spells lua there is only value 1 (i cannot put 0.5), and on 0 there is no regeneration.

DefineVariables("Mana", {Max = 0, Value = 64, Increase = 1, Enable = false}, "Speed", "ShadowFly", {Max = 2}, "Level")

**Comment by timfel** [comment]
You can use IncreaseFrequency=3, then it will not increase 1 time per second but 1 time every 3 seconds.

**Comment by timfel** [comment]
Fixed by your patch
