### ISSUE TITLE
font 5x8 pix is cut - letter w W m M

### ISSUE THREAD

**Issue by Lagi7** [Wargus/war1gus#235]
wide letters from 5x8 font are cut. 
 like - w W m M
https://i.imgur.com/bOaSG9a.png

i think the game is taking each letter as 4x8 instead 5x8

-----------------------

line 32 fonts.lue
CFont:New("game", CGraphic:New("contrib/fonts/5x8.png", 5, 8))

if we increase x to 6 it break all strings in game, so value 5 is good.
smaller font take 4 pixels (even if the name of font file is 3x5) but thats ok.

**Comment by timfel** [comment]
Fixed on master
