### ISSUE TITLE
Level Editor needs alot of work

### ISSUE THREAD

**Issue by timfel** [Wargus/war1gus#40]
The Level editor as it stands right now is Practically unusuable. Its very difficult to see or edit anything And saving maps resulted in game saves rather than map saves.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2015-09-09T20:01:29Z
 * owner: zombie-ryushu
 * the launchpad url was https://bugs.launchpad.net/bugs/1493987

**Comment by timfel** [comment]
This is still work in progress, but as of right now we can actually create dungeon, forest and swamp maps. Due to limitations of the engine, the tilesets behave differently from the original. Bridges end in the water near the coast, rather than stretch on to land. And the dungeon tileset wasn't actually meant to be used for ordinary maps with buildings and such, so it's kind of hacked. In dungeons, there are no forests, so we chop up barrels and wooden tables and such for wood, but I think that works well.

**Comment by Zombie-Ryushu** [comment]
Can you create a map from scratch and have it function correctly?

**Comment by timfel** [comment]
Except for the computer AI, yes

**Comment by Zombie-Ryushu** [comment]
The issue is, I'd like to start testing multiplayer functionality.

**Comment by Zombie-Ryushu** [comment]
How can the Computer AI and Stock maps be fixed?

**Comment by timfel** [comment]
Well, multiplayer works (both with the extracted maps and with hand-made), I've played a few skirmish battles with colleagues. About the AI, I'm  not sure what change broke it, this is next on my list

**Comment by timfel** [comment]
AI should work now in the stock maps and editor.
