### ISSUE TITLE
Solo game - Number of opponents ignored

### ISSUE THREAD

**Issue by asbernardi** [Wargus/war1gus#407]
Hi!
If you play a 'solo game' and set 1 opponent, this setting is ignored. Example maps:
- Forest1
- Forest2

**Comment by Lagi7** [comment]
hmm... i guess war2gus work properly so maybe we need to compare the 2x files what's different

**Comment by timfel** [comment]
In `wc1.lua` where it says

```lua
if (nump == 0) then nump = 15 end
```

it should instead say
```lua
if (nump == -1) then nump = 15 else nump = nump + 1 end
```

**Comment by timfel** [comment]
Fixed.
