### ISSUE TITLE
Solo game - AI freezes after scenario restart

### ISSUE THREAD

**Issue by asbernardi** [Wargus/war1gus#408]
Hi!
If you play a 'solo game' and restart scenario, then AI freezes. It only harvests gold once and freezes.
It happens at least in following maps:
- Forest1
- Forest2.

Thanks!

**Comment by Lagi7** [comment]
also happen if you go back to menu and start new solo game. You need to restart the game.

timfelgentreff
 — 
Wczoraj o 21:21
yeah, some variable isn't reset properly after the game. not sure what it is, something in lua definitely

**Comment by timfel** [comment]
we need to add this to the end of  `wc1.lua` (copied from `wc2.lua` in wargus)

```lua

function CleanGame_Lua()
	print("game ends")
	ReInitAiGameData()	
end
```

**Comment by timfel** [comment]
Fixed
