### ISSUE TITLE
Sound effects wrong for winning and losing levels

### ISSUE THREAD

**Issue by timfel** [Wargus/war1gus#41]
I have the "Floppy Disk" Version of Warcraft I, and that has certain implications. The videos were cut down into stills, and the voice acting for the missions was removed. However the speaking for the Victory and Defeat roles remained. During briefings, sometimes in latter missions I hear the Victory and Defeat Voice acting played.  But I don't hear it during victory or defeat.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2015-09-09T20:10:54Z
 * owner: zombie-ryushu
 * the launchpad url was https://bugs.launchpad.net/bugs/1493988

**Comment by timfel** [comment]
(by zombie-ryushu)
Please be patient, the data may take a couple of minutes to extract...
Not a wav file: intro_2
Not a wav file: intro_3
Not a wav file: intro_4
Not a wav file: intro_5
Not a wav file: ../campaigns/human/01_intro
Not a wav file: ../campaigns/human/02_intro
Not a wav file: ../campaigns/human/03_intro
Not a wav file: ../campaigns/human/04_intro
Not a wav file: ../campaigns/human/05_intro
Not a wav file: ../campaigns/human/06_intro
Not a wav file: ../campaigns/human/07_intro
Not a wav file: ../campaigns/human/08_intro
Not a wav file: ../campaigns/human/09_intro
Not a wav file: ../campaigns/human/10_intro
Not a wav file: ../campaigns/human/11_intro
Not a wav file: ../campaigns/human/12_intro
Not a wav file: ../campaigns/orc/01_intro
Not a wav file: ../campaigns/orc/02_intro
Not a wav file: ../campaigns/orc/03_intro
Not a wav file: ../campaigns/orc/04_intro
Not a wav file: ../campaigns/orc/05_intro
Unknown flags b
Unknown flags 1f
Unknown flags 1

**Comment by timfel** [comment]
(by zombie-ryushu)
Additionally, I now can't run the game because I have no ruins file.
data.wc1/tilesets/swamp/neutral/buildings/ruins_1x1.png: cannot open `data.wc1/tilesets/swamp/neutral/buildings/ruins_1x1.png' (No such file or directory)

**Comment by Zombie-Ryushu** [comment]
I have all the voice clips in the Floppy version accounted for, however, they play at the wrong times.

**Comment by timfel** [comment]
Winning and losing voiceover should now play correctly
