### ISSUE TITLE
Error on exiting the game 

### ISSUE THREAD

**Issue by xcom169** [Wargus/war1gus#412]
Hello All

I always get this strange error on exiting the game on Win 10 with the latest portable version: 

![image](https://user-images.githubusercontent.com/17802090/191469108-d1cf683e-c6ff-4ec6-90be-52087116fbb0.png)
[War1GUS.zip](https://github.com/Wargus/war1gus/files/9615216/War1GUS.zip)

**Comment by Lagi7** [comment]
I have this message display for me so many times, that now i just assume its part of the game. Or no launch warning like "you broke the game, go back with your code modification"
