### ISSUE TITLE
Audio CD

### ISSUE THREAD

**Issue by Gr33nEyes** [Wargus/war1gus#413]
Will you add support of Audio CD tracks (converted in OGG Vorbis of course?)

**Comment by timfel** [comment]
Warcraft 1 does not have all tracks as audio tracks, most of the tracks only ever existed as midi. Only the first 4 or 5 tracks are available as audio tracks, so it's not enough. It's easy enough to set up e.g. a Roland SC-55 midi font on your system to make it sound great (look at e.g. https://coolsoft.altervista.org/en/virtualmidisynth if you're on Windows)
