### ISSUE TITLE
No ability to play intro cinematic or any cutscenes? 

### ISSUE THREAD

**Issue by CRYPTark01** [Wargus/war1gus#415]
Really? Where is the intro cinematic? What does the "Play intro" setting even do when there isn't any intro that plays?

**Comment by timfel** [comment]
The intro plays for most people, as can be seen for example in this video: https://youtu.be/-9Y9KtXltMA?t=98

Once you've extracted the game the first time you start it, the intro will play.

**Comment by CRYPTark01** [comment]
> The intro plays for most people, as can be seen for example in this video: https://youtu.be/-9Y9KtXltMA?t=98
> 
> Once you've extracted the game the first time you start it, the intro will play. Without any further info about your system and how you installed War1gus there is not much I can do to help you, since it works for everyone else.

It doesn't though. I have gone from a fresh GOG install to this and the intro cutscene never plays no matter what I do. The version you show in that video is not the version I am using. I am using the latest and in the latest it does not work. Can you please fix it? I would love to play the game but I need the intro cutscene.

**Comment by timfel** [comment]
> Without any further info about your system and how you installed War1gus there is not much I can do to help you

You still haven't told me where and how you installed this ;) Is this on Linux, macOS, Windows? Portable or global installation? Run from command line or from launcher? Did you review https://youtu.be/6a4dy16q49c and check the extraction and error logs like it shows in the video?

**Comment by CRYPTark01** [comment]
> > Without any further info about your system and how you installed War1gus there is not much I can do to help you
> 
> You still haven't told me where and how you installed this ;) Is this on Linux, macOS, Windows? Portable or global installation? Run from command line or from launcher? Did you review https://youtu.be/6a4dy16q49c and check the extraction and error logs like it shows in the video? Without all of this info, there is very little I can do to understand your issue.

I did it according the instructions with the GOG backup installer and the War1gus portable installer. I attached the extraction log and error logs. No matter what I do I cannot get the intro video to play. I see the blizzard logo and the blizzard noise start to increase and then it just flashes to the main menu. 
[War1gus-extraction.log](https://github.com/Wargus/war1gus/files/10405381/War1gus-extraction.log)
[stdout.txt](https://github.com/Wargus/war1gus/files/10405392/stdout.txt)
[stderr.txt](https://github.com/Wargus/war1gus/files/10405395/stderr.txt)

**Comment by timfel** [comment]
Looks like you have spaces in your installation path. That doesn't work correctly. Please use a path that doesn't have spaces.

**Comment by CRYPTark01** [comment]
> Looks like you have spaces in your installation path. That doesn't work correctly. Please use a path that doesn't have spaces.

You are a lifesaver. It now plays them properly. Thank you sir.
