### ISSUE TITLE
Custom Map issues

### ISSUE THREAD

**Issue by timfel** [Wargus/war1gus#43]
I was playing a Custom map, and ran some tests on its behaviour. I set a four force battle. Three computer forces and one Player Force. Only one of the Computer Forces used the wc1-land-attack script. The other three were passive. They created four squares of cobbled road and then gathered gold and wood

I then switched one of the forces to be rescue-active. The rescue active force was not hostile to the player force, but was not rescuable. As with all but one computer force, They created four squares of cobbled road and then gathered gold and wood, but nothing else.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2015-09-10T10:20:42Z
 * owner: zombie-ryushu
 * the launchpad url was https://bugs.launchpad.net/bugs/1494238

**Comment by timfel** [comment]
(by timfelgentreff)
Can you attach the map?

**Comment by timfel** [comment]
(by zombie-ryushu)
Here's part of it.

**Comment by timfel** [comment]
(by zombie-ryushu)

**Comment by timfel** [comment]
(by zombie-ryushu)

**Comment by timfel** [comment]
(by zombie-ryushu)

**Comment by Zombie-Ryushu** [comment]
Custom maps are unplayable.

**Comment by Zombie-Ryushu** [comment]
Rescue Active does not work Properly. Attempting to set a force to be Rescue Active will result in the force being inert. Rescue Active should result in an allied force.

**Comment by timfel** [comment]
With the latest commits, I created a map in the editor with a rescue-active force, which was allied and helped me attack the other computer player. However, rescue of a rescue-passive force did not work
