### ISSUE TITLE
War1gus-portable-3.3.2 - Crashes when trying to convert GOG version files

### ISSUE THREAD

**Issue by SilentMRG** [Wargus/war1gus#442]
Hello...

Extracting the files worked well with the "setup_warcraft_orcs__humans_1.2_(28330)" installer, however, when converting the files, the following problem occurs:

  Problem Event Name: BEX
  Application Name: war1tool.exe
  Application Version: 0.0.0.0
  Application Timestamp: 62f3ffad
  Fault Module Name: ucrtbase.DLL
  Fault Module Version: 10.0.14393.2630
  Fault Module Timestamp: 5bbec6e6
  Exception Offset: 00087fd4
  Exception Code: c0000417
  Exception Data: 00000000
  Operating system version: 6.1.7601.2.1.0.256.1
  Location Identification: 1046
  Additional Information 1: b747
  Additional Information 2: b747f80c6e9667101e8ebbce34750c90
  Additional Information 3: 2484
  Additional Information 4: 2484fa43a29363e7163fae090c2a77ae

Note: Wargus-portable-3.3.2 worked perfectly! I don't know why War1gus-portable-3.3.2 is showing this.

Thanks in advance!

**Comment by SilentMRG** [comment]
Well, I hope the information contained in the image below helps in some way.
![0](https://github.com/Wargus/war1gus/assets/62117728/8dc98422-2584-4b9d-bf8a-b849d60579c6)
I'm a layman on the subject, but, in my ignorance, the last line says that there was an overload or something like that.

**Comment by SilentMRG** [comment]
So it looks like the problem was with the length of the folder name. I shortened the name to something like "War1gus332" and the file conversion went well until the end, however, when the conversion was complete I got the error "war1tool" that the "Memory could not be read or something", anyway way, in cmd, it was written that "the conversion process was complete and that I would no longer need to run it, etc....". Anyway, the game started normally, so I didn't understand this error. 

Just two questions: Is there no support for 16:9 screens? The game is shot in 4:3, which is a shame. And how do I start War1gus/Wargus in full screen? Whenever I select the full screen option in Wargus, it starts in a window. Well, I'm on Windows 7.

Thanks man! I'm going to star the repositories... Your projects have a lot of potential. =D

**Comment by timfel** [comment]
Hi. Yeah, there are some issues with long path names or weird characters in paths. Also, note that we no longer support Windows 7. I think we have already started using stuff that is only available in Windows 8 and later, so it may work for you, or not, no idea.

The Stratagus engine supports any kind of resolution. You can change it to whatever you want in your `wc1/preferences.lua` file in you portable installation directory.

**Comment by SilentMRG** [comment]
I understand. As for it working on Windows 7, it works great, except that sometimes, between missions, I get this error: https://github.com/Wargus/war1gus/issues/438
And sometimes this error occurs when I close the engine.

And thanks again for the information!

**Comment by SilentMRG** [comment]
> The Stratagus engine supports any kind of resolution. You can change it to whatever you want in your `wc1/preferences.lua` file in you portable installation directory. Change the `wc1.preferences.VideoWidth` and `wc1.preferences.VideoHeight` values to whatever you want. Note that of course the UI will look more and more strange the farther away from the true Warcraft 1 aspect ratio you go. The assets were never meant for different resolutions.

Consider taking a look at this project: https://github.com/FunkyFr3sh/cnc-ddraw

And implement it in the engine. It handles any resolution very well and doesn't leave that weird look. Furthermore, there are interesting filters. Best of all, things work via GDI, OpenGL, Direct3D 9 and DirectDraw which increases support for older operating systems. It's a jack of all trades wrapper! If you understand me. =)

**Comment by timfel** [comment]
(Also, we are using SDL, not direct draw)

**Comment by timfel** [comment]
Ah, I see where your confusion comes from: me saying we're not supporting Windows 7. That has nothing to do with the graphics backend, SDL2 would happily support Windows XP and maybe older systems even. We the developers just choose to use C++ language features that are only available in newer compilers that no longer produce binaries for old systems. There's no magic fix for that ;)

**Comment by SilentMRG** [comment]
I truly understand! But cnc-ddraw can do full screen upscaling at any resolution and it looks nice. Anyway, it was just a suggestion. Thank you for your attention! =)
