### ISSUE TITLE
units attacking and are position in wrong places

### ISSUE THREAD

**Issue by Lagi7** [Wargus/war1gus#455]
f.ex. it appears on screen that units are attacking from 2 tiles away

or

they hitting empty space, while the representing unit is on different location

![image](https://github.com/Wargus/war1gus/assets/93911529/7fa5d4ab-a172-4a89-8311-3ebc60a49912)

on this screen the top grunt is probably located near the TH but the graphic is dispaly in odd location

![image](https://github.com/Wargus/war1gus/assets/93911529/e3a43fc7-e71f-4afc-bf1d-94f3e451db3b)

![image](https://github.com/Wargus/war1gus/assets/93911529/bf9f31ff-1a28-4f35-80c4-fd80a8b1309d)

swordsman is hitting south tile, while orc is on the same tile as footman
check where the blood is shed

**Comment by Jarod42** [comment]
Issue found (but not yet the correct fix)
move animation action is buggy:
last wait (after fully tile move) starts a move again (with sub offset to last position).
and so the breakable wait in animation is not from a correct state.
