### ISSUE TITLE
Garona Northshire Abbey ends in constant defeat.

### ISSUE THREAD

**Issue by timfel** [Wargus/war1gus#72]
Garona Northshire Abbey mission ends in constant defeat. Any attempt you make to start the mission ends in defeat.

------------------------------------
Imported from Launchpad using lp2gh.

 * date created: 2015-10-21T21:39:59Z
 * owner: zombie-ryushu
 * the launchpad url was https://bugs.launchpad.net/bugs/1508691

**Comment by timfel** [comment]
(by timfelgentreff)
Hm, I don't experience that. I did have a problem in that you couldn't reach garona, because the door is not passable and cannot be destroyed. I have no solution yet for destroying doors, so right now you can just walk over it.

**Comment by Zombie-Ryushu** [comment]
Re-extraction of maps with a clean extraction works. The Garona map is playable, but doors are transparent.

**Comment by timfel** [comment]
Fixed in #79
