### ISSUE TITLE
Ship some skirmish maps

### ISSUE THREAD

**Issue by timfel** [Wargus/war1gus#76]
Warcraft 1 shipped with a bunch of skirmish maps, but these are in the hand-coded tileset that is not compatible with the editor. Also, they are very small (all WC1 maps are 64x64).

It would be nice to add some contributed maps that can be used directly to play games in various sizes for 2-8 players or so.

**Comment by Zombie-Ryushu** [comment]
I second that the Skirmish maps are broken, and this affects my ability to test multiplayer.
