### ISSUE TITLE
Destroyed Doors can create graphic glitches

### ISSUE THREAD

**Issue by Zombie-Ryushu** [Wargus/war1gus#80]
Destroyed Doors can create graphic glitches. The door will "clip" a "hall of mirrors effect" over that tile.

**Comment by timfel** [comment]
Did you use the most recent stratagus? I had to add code changes to the engine to make this work

**Comment by timfel** [comment]
If you did, than I missed a case. Could you tell me which level + doors, or add a screenshot?

**Comment by Zombie-Ryushu** [comment]
It was the first cell you pass on the Eastern side. It was the bottom door.

**Comment by timfel** [comment]
Which level?

**Comment by Zombie-Ryushu** [comment]
Northshire Abbey, Garona's level.

**Comment by timfel** [comment]
Hm, I extensively tested that level, and with the engine fixes, I don't see any more glitches. Did you use Stratagus master?

**Comment by Zombie-Ryushu** [comment]
I'll give it one more attempt.

**Comment by Zombie-Ryushu** [comment]
Okay, so the latest git check out resolved it.
