### ISSUE TITLE
Medivh does not gain Spells researched at Warlock Tower

### ISSUE THREAD

**Issue by Zombie-Ryushu** [Wargus/war1gus#82]
Medivh does not gain Spells researched at the Warlock Tower. Medievh counts as an Orcish Warlock unit. However he does not benefit from benefit from spells researched at the tower. In his own level in the campaign, he uses his abilities as a Warlock to hobble the player.

**Comment by timfel** [comment]
Medivh does gain those spells now. How to get him to autocast, I have to understand the autocasting rules in Stratagus.

**Comment by timfel** [comment]
He seems to autocast now, although I'm not sure that's better...
