### ISSUE TITLE
Computer forces will block themselves in, failing to put space

### ISSUE THREAD

**Issue by Zombie-Ryushu** [Wargus/war1gus#87]
Computer forces will block themselves in, failing to put space between buildings. They will pile buildings in rows creating situations where their units are fully blocked on all sides from entering or exiting an area of town.

**Comment by timfel** [comment]
This should be better now with an additional rule for the AI to leave 1 tile of space between buildings, although it may still happen that units find themselves surrounded by buildings and forest
