### ISSUE TITLE
Cannot "draw" cobbled road by click and drag.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [Wargus/war1gus#88]
I cannot "draw" cobbled road by click and drag. I seemingly have to click each individual tile one square at a time making the task take longer than it did in the original game.

**Comment by timfel** [comment]
I have enabled popups by default now for war1gus. Click+drag would require some changes in the engine that I'm not sure would be worthwhile. An alternative is to hold shift while setting a road, and then semi-slowly dragging the mouse
