### ISSUE TITLE
War1gus extractor (wartool) not running during installation process

### ISSUE THREAD

**Issue by DinkyDyeAussie** [Wargus/war1gus#90]
I have tried installing war1gus, and during this process the cmd.exe program starts so wartool can start it's extraction of the Warcraft data off the cd...well...it should...but doesn't. Instead, at first I got a message box saying I needed MSVCP140D.dll to run wartool. No problem. Downloaded the file, and placed it in my Windows/System32 folder, did a restart, and tried again. Now it's giving me the "0xc000007b" error say it has an error and cannot start...

Anyone got any ideas how to help?

**Comment by timfel** [comment]
mh, i have not seen this before. in the installer, it should have printed the invocation for war1tool, can you run this in a fresh commandprompt and post the output?

**Comment by DinkyDyeAussie** [comment]
I shall when I get the opportunity.

**Comment by DinkyDyeAussie** [comment]
It's saying "ucrtbased.dll" is missing now...Never had this problem with wartool for wargus.

**Comment by DinkyDyeAussie** [comment]
OK so I got it to work and the data was extracted. War1tool errored out at the end saying it wrote to memory after it was not allowed to or something. It did fully complete extraction though.

Glad it works but after playing wargus/warcraft 2 this game looks so primitive lol.

**Comment by timfel** [comment]
Ok, ucrtbased seems to be some stuff they introduced with windows 10 ... i should set the nightly builds to build windows 7 compatible, i guess?

And yes, it looks primitive, but i still like some of the ideas they dropped in WC2, like roads and summoning daemons and elementals, and also dungeons

**Comment by timfel** [comment]
I'm running the visual studio runtime installer now during installation if necessary, so that should take care of the missing dlls

**Comment by DinkyDyeAussie** [comment]
Cool man I will use that if I ever have to reinstall it again.
