### ISSUE TITLE
Game Freezes due to Network De-sync

### ISSUE THREAD

**Issue by Zombie-Ryushu** [Wargus/war1gus#91]
I have an issue with multiplayer as of the latest GIT. The clients joined to the master server freeze upon the game actually starting in a network game. The master server displays a timer that it is waiting for a response.

**Comment by Zombie-Ryushu** [comment]
This is still an issue, please confirm that network game freeze on launch.

**Comment by timfel** [comment]
I cannot reproduce this issue at least on Windows right now. Testing on Linux will have to wait until after new year, because I won't be working on this over the next ~2 weeks

**Comment by Zombie-Ryushu** [comment]
The problems seem to start the moment the two players can see each other. I can't get a Stack Trace because the game doesn't actually crash

**Comment by Zombie-Ryushu** [comment]
Have you looked into the networking issue?

**Comment by timfel** [comment]
I have just played a network game, and did not experience this issue. When you notice it, could you attach a gdb? You should be able to do so by running `sudo gdb -p $(ps -o pid -C stratagus | tail -1)` when it hangs. In the prompt that appears, type `bt` to get a trace.

**Comment by Zombie-Ryushu** [comment]
The issue is resolved. The two installs had left over files in the lua scripts from older instances of the game.
