### ISSUE TITLE
Seg Fault.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [Wargus/war1gus#92]
Program received signal SIGSEGV, Segmentation fault.
0x00000000006a99ce in CColor::operator SDL_Color() const ()
(gdb) bt
#0  0x00000000006a99ce in CColor::operator SDL_Color() const ()
#1  0x000000000061c4ab in void std::_Construct<SDL_Color, CColor>(SDL_Color*, CColor const&) ()
#2  0x00000000006b48b9 in SDL_Color* std::__uninitialized_copy<false>::__uninit_copy<CColor const*, SDL_Color*>(CColor const*, CColor const*, SDL_Color*) ()
#3  0x00000000006b3772 in SDL_Color* std::uninitialized_copy<CColor const*, SDL_Color*>(CColor const*, CColor const*, SDL_Color*) ()
#4  0x00000000006b1b7c in SDL_Color* std::__uninitialized_copy_a<CColor const*, SDL_Color*, SDL_Color>(CColor const*, CColor const*, SDL_Color*, std::allocator<SDL_Color>&) ()
#5  0x00000000006b109c in void std::vector<SDL_Color, std::allocator<SDL_Color> >::_M_range_initialize<CColor const*>(CColor const*, CColor const*, std::forward_iterator_tag) ()
#6  0x00000000006b018d in void std::vector<SDL_Color, std::allocator<SDL_Color> >::_M_initialize_dispatch<CColor const*>(CColor const*, CColor const*, std::__false_type) ()
#7  0x00000000006aedf8 in std::vector<SDL_Color, std::allocator<SDL_Color> >::vector<CColor const*>(CColor const*, CColor const*, std::allocator<SDL_Color> const&) ()
#8  0x00000000006ac4eb in VideoDrawChar(CGraphic const&, int, int, int, int, int, int, CFontColor const&) ()
#9  0x00000000006b05c9 in unsigned int CFont::DrawChar<false>(CGraphic&, int, int, int, CFontColor const&) const ()
#10 0x00000000006af50e in int CLabel::DoDrawText<false>(int, int, char const*, unsigned long, CFontColor const*) const ()
#11 0x00000000006ad124 in CLabel::Draw(int, int, std::string const&) const ()
#12 0x000000000064e8f7 in CPopupContentTypeButtonInfo::Draw(int, int, CPopup const&, unsigned int, ButtonAction const&, int*) const ()
#13 0x00000000006354f0 in DrawPopup(ButtonAction const&, CUIButton const&, int, int) ()
#14 0x0000000000635bea in CButtonPanel::Draw() ()
#15 0x0000000000616546 in UpdateDisplay() ()
#16 0x00000000006169d0 in DisplayLoop() ()
#17 0x00000000006169e2 in SingleGameLoop() ()
#18 0x0000000000616a88 in GameMainLoop() ()
#19 0x00000000005834e1 in StartMap(std::string const&, bool) ()
#20 0x00000000006d00f4 in tolua_stratagus_StartMap00(lua_State*) ()
#21 0x00000034fc40c3f9 in ?? () from /usr/lib64/liblua.so.5.1
#22 0x00000034fc416a1f in ?? () from /usr/lib64/liblua.so.5.1
#23 0x00000034fc40c82d in ?? () from /usr/lib64/liblua.so.5.1
#24 0x00000034fc40bb4b in ?? () from /usr/lib64/liblua.so.5.1
#25 0x00000034fc40c99b in ?? () from /usr/lib64/liblua.so.5.1
#26 0x00000034fc40883c in lua_pcall () from /usr/lib64/liblua.so.5.1
#27 0x0000000000615eef in LuaCallback::run(int) ()
#28 0x0000000000660cab in LuaActionListener::action(std::string const&) ()
#29 0x000000000059e118 in gcn::Widget::generateAction() ()
#30 0x00000000005a135f in gcn::Button::mouseClick(int, int, int, int) ()
#31 0x000000000059dbfc in gcn::Widget::_mouseInputMessage(gcn::MouseInput const&) ()
#32 0x00000000005a2aca in gcn::Container::_mouseInputMessage(gcn::MouseInput const&) ()
#33 0x0000000000595768 in gcn::Gui::logic() ()
#34 0x0000000000660b07 in handleInput(SDL_Event const*) ()
#35 0x00000000006c78f6 in WaitEventsOneFrame() ()
#36 0x0000000000669a1e in MenuScreen::run(bool) ()
#37 0x00000000006fa50e in tolua_stratagus_CMenuScreen_run00(lua_State*) ()
#38 0x00000034fc40c3f9 in ?? () from /usr/lib64/liblua.so.5.1
#39 0x00000034fc416a6a in ?? () from /usr/lib64/liblua.so.5.1
#40 0x00000034fc40c82d in ?? () from /usr/lib64/liblua.so.5.1
#41 0x00000034fc40bb4b in ?? () from /usr/lib64/liblua.so.5.1
#42 0x00000034fc40c99b in ?? () from /usr/lib64/liblua.so.5.1
#43 0x00000034fc40883c in lua_pcall () from /usr/lib64/liblua.so.5.1
#44 0x0000000000615eef in LuaCallback::run(int) ()
#45 0x0000000000660cab in LuaActionListener::action(std::string const&) ()
#46 0x000000000059e118 in gcn::Widget::generateAction() ()
#47 0x00000000005a135f in gcn::Button::mouseClick(int, int, int, int) ()
#48 0x000000000059dbfc in gcn::Widget::_mouseInputMessage(gcn::MouseInput const&) ()
#49 0x00000000005a2aca in gcn::Container::_mouseInputMessage(gcn::MouseInput const&) ()
#50 0x0000000000595768 in gcn::Gui::logic() ()
#51 0x0000000000660b07 in handleInput(SDL_Event const*) ()
#52 0x00000000006c78f6 in WaitEventsOneFrame() ()
#53 0x0000000000669a1e in MenuScreen::run(bool) ()
---Type <return> to continue, or q <return> to quit---
#54 0x00000000006fa50e in tolua_stratagus_CMenuScreen_run00(lua_State*) ()
#55 0x00000034fc40c3f9 in ?? () from /usr/lib64/liblua.so.5.1
#56 0x00000034fc416a1f in ?? () from /usr/lib64/liblua.so.5.1
#57 0x00000034fc40c82d in ?? () from /usr/lib64/liblua.so.5.1
#58 0x00000034fc40bb4b in ?? () from /usr/lib64/liblua.so.5.1
#59 0x00000034fc40c99b in ?? () from /usr/lib64/liblua.so.5.1
#60 0x00000034fc40883c in lua_pcall () from /usr/lib64/liblua.so.5.1
#61 0x0000000000615eef in LuaCallback::run(int) ()
#62 0x0000000000660cab in LuaActionListener::action(std::string const&) ()
#63 0x000000000059e118 in gcn::Widget::generateAction() ()
#64 0x00000000005a135f in gcn::Button::mouseClick(int, int, int, int) ()
#65 0x000000000059dbfc in gcn::Widget::_mouseInputMessage(gcn::MouseInput const&) ()
#66 0x00000000005a2aca in gcn::Container::_mouseInputMessage(gcn::MouseInput const&) ()
#67 0x0000000000595768 in gcn::Gui::logic() ()
#68 0x0000000000660b07 in handleInput(SDL_Event const*) ()
#69 0x00000000006c78f6 in WaitEventsOneFrame() ()
#70 0x0000000000669a1e in MenuScreen::run(bool) ()
#71 0x00000000006fa50e in tolua_stratagus_CMenuScreen_run00(lua_State*) ()
#72 0x00000034fc40c3f9 in ?? () from /usr/lib64/liblua.so.5.1
#73 0x00000034fc416a1f in ?? () from /usr/lib64/liblua.so.5.1
#74 0x00000034fc40c82d in ?? () from /usr/lib64/liblua.so.5.1
#75 0x00000034fc40bb4b in ?? () from /usr/lib64/liblua.so.5.1
#76 0x00000034fc40c99b in ?? () from /usr/lib64/liblua.so.5.1
#77 0x00000034fc40883c in lua_pcall () from /usr/lib64/liblua.so.5.1
#78 0x000000000061c826 in LuaCall(int, int, bool) ()
#79 0x000000000061cb8f in LuaLoadFile(std::string const&, std::string const&) ()
#80 0x0000000000630d53 in MenuLoop() ()
#81 0x000000000063179e in stratagusMain(int, char**) ()
#82 0x0000000000615fd4 in main ()
(

**Comment by Zombie-Ryushu** [comment]
Game is completely broken.

**Comment by timfel** [comment]
Interesting, I wonder why this doesn't happen on windows. Anyway, I can reproduce this on Ubuntu, I'll look into it.

**Comment by timfel** [comment]
Ok, fixed as of 6af99b1
