### ISSUE TITLE
Summoned Daemons and Water Elementals do not reflect the Force that summoned them.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [Wargus/war1gus#94]
Summoned Daemons and Water Elementals do not reflect the Force that summoned them. Water Elementals will always be blue, Daemons will always be red regardless of the Warlock who summoned them.

**Comment by timfel** [comment]
What should they be? If we do the color swap for them, then they'll be entirely colored, which probably won't look good, will it?

**Comment by Zombie-Ryushu** [comment]
The behavior of the original game was to color swap them, there could be Red Water Elementals and Blue Daemons.  Do you have any good alternatives?

**Comment by timfel** [comment]
Ah, if that was the original behavior, I can do that...

**Comment by timfel** [comment]
Ok, it's done, and I've also done the color swapping for spiders, scorpions, and ogres.
