### ISSUE TITLE
Auto-Casting does to not do much

### ISSUE THREAD

**Issue by Zombie-Ryushu** [Wargus/war1gus#96]
I attempted to enable Auto-casting of Daemons on my Warlocks, dispite having more than enough mana, the Warlocks did not create more Daemons. The icon for it did flash however. Am I just not understanding what this is for?

**Comment by timfel** [comment]
I have set it up so that daemons are never auto-summoned. It just costs a lot of mana. Auto-casting just means that, if there are auto-cast rules, it will do it. It is enabled for spiders/scorpions, raise dead, and healing.

**Comment by Zombie-Ryushu** [comment]
I will give it a try on my test map.

**Comment by Zombie-Ryushu** [comment]
Okay, the Autocast only works when a Warlock or Necromancer is immediately threatened by the presence of enemy units. This may not be ideal partically because Warlocks and similar magic units tend to send units long distances to avoid enemies attacking the Warlock.

**Comment by timfel** [comment]
Indeed, I have set it up so that casting only happens if enemy units are near for these offensive spells. Healing and Invisibility are cast regardless. The problem with the Necromancers is one that I have yet to figure out, but for the offensive spells, why would you want the warlock to just randomly summon spiders that just sit there?

**Comment by Zombie-Ryushu** [comment]
To send them a long distance without being damaged. This is Medivh's behavior in the original game.

**Comment by timfel** [comment]
Yes, I would want to add that for the AI. But I wouldn't want my own units to just hurry off and attack the enemy (and that wouldn't be possible in any case, because there is no AI controlling my units)

**Comment by Zombie-Ryushu** [comment]
think this situation is better addressed by fixing the Catapult behavior not to fire on your own nearby units, which is what the real danger is.

**Comment by timfel** [comment]
I'm tracking the catapult issue in #63 and have a possible fix in https://github.com/Wargus/stratagus/pull/174

**Comment by timfel** [comment]
Catapult behavior should be fixed. Units can still run into the path of a projectile, but the catapult will only initiate a shot if there are no friendly units next to the target.
