### ISSUE TITLE
Game Freezes when victory condtion happens.

### ISSUE THREAD

**Issue by Zombie-Ryushu** [Wargus/war1gus#97]
The Game Freezes when a victory is Achieved and the next level is being loaded. The game freezes loading terrain.png.

**Comment by timfel** [comment]
Is that using the latest stratagus master? Because the latest commit fixed exactly this issue for me.

**Comment by Zombie-Ryushu** [comment]
I'm rebuilding everything, my latest git checkout deleted a bunch of stuff in war1gus.

**Comment by Zombie-Ryushu** [comment]
Issue resolved by an Asset rebuild. I am still getting inappropriate Sound samples played by the Floppy Version. (The Ending Victory plays when a normal level is beaten, for example.)
