### ISSUE TITLE
Summoned Monsters have no Magic Meter

### ISSUE THREAD

**Issue by Zombie-Ryushu** [Wargus/war1gus#99]
Summoned Monsters have no Magic Meter that slowly winds down giving an indication when the monster will perish of its own accord. They only have an HP meter.

**Comment by timfel** [comment]
I discussed this with @Andrettin, and it will require some work in the engine.

**Comment by timfel** [comment]
I added the magic meter, but it still needs some work to function properly across savegames and there are some other glitches

**Comment by timfel** [comment]
Fixed.
